services:
  - type: web_service
    name: sos-encanador-api
    env: node
    root: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    healthCheckPath: /

  - type: static_site
    name: sos-encanador-web
    env: node
    root: apps/web
    buildCommand: npm install && npm run build
    publishPath: dist
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://encanador-api.onrender.com
