services:
  - type: web_service
    name: sos-encanador-conecta
    env: node
    root: .
    buildCommand: npm install && npm run build
    startCommand: npm run start
    plan: free
    healthCheckPath: /
